apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
    - name: probes
      port: 9091
      targetPort: probes
